### ISSUE TITLE
Update to Ace version 1.9.5?

### ISSUE THREAD

**Issue by sabracrolleton** [rabbibotton/clog-ace#2]
Just checking since the version clog is pulling is 1.6.0.

**Comment by rabbibotton** [comment]
That must be what the CDN had online, I plan on setting things up better to allow a local copy of Ace and others.

**Comment by sabracrolleton** [comment]
https://cdnjs.com/libraries/ace is showing 1.9.5

**Comment by rabbibotton** [comment]
Updated it to 1.9.5

Hopefully in next days will have a more full solution

**Comment by rabbibotton** [comment]
I have modified clog-ace so that if you copy the www/clog-ace dir to your static files it will be used instead of the internet version (which is now 1.9.5)

**Comment by sabracrolleton** [comment]
Thank you.
